#!/bin/bash

command -v fzf

if [ $? -eq 1 ]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    exit 0
else
    FZF=true
fi

DEV=$(echo "DEV
RELEASE" | fzf --reverse --no-mouse --height=15 --bind=left:page-up,right:page-down)


ls -d example/*/* practice/*/* | awk -F' ' '{print $0}' > list

SELECTED=$(cat list | fzf --reverse --no-mouse --height=15 --bind=left:page-up,right:page-down)
echo $SELECTED
if [ ${DEV} == "DEV" ]; then
    go run ${SELECTED}/*
else
    ## for using private git
    # env GIT_TERMINAL_PROMPT=1 go get ...

    GOURL=$(git config --get remote.origin.url | head -1 | sed -e "s/https:\/\///" | sed -e "s/.git/\//")

    go run ${GOURL}/${SELECTED}
fi

rm -f list

